
[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"

[window]
opacity = 0.91

[general]
# import = ["/home/alex/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
import = ["/home/alex/.config/alacritty/nord.toml"]
